openapi: 3.0.3
info:
  title: Accounts Service API
  version: '1.0'
  description: >-
    This is a RESTful service that collects accounts information received from
    Vend.
  x-logo:
    url: ''
servers:
  - url: 'http://localhost:8080/api'
    description: ''
    x-last-modified: 1617082679035
paths:
  /accounts:
    get:
      tags:
        - Accounts
      responses:
        '200':
          content:
            application/json:
              schema:
                description: ''
                type: array
                items:
                  $ref: '#/components/schemas/Account'
                externalDocs:
                  description: ''
                  url: ''
                example: ''
              example: ''
          description: An array of all registered customer accounts.
          x-last-modified: 1617081537029
      operationId: get accounts
      description: Get all registered customer accounts.
    post:
      requestBody:
        description: The details for the account.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
        required: true
      tags:
        - Accounts
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
          description: >-
            <p>Account successfully created.</p> <p>The URI of new account is
            available in the <code>uri</code> field of the response.  The new
            account is returned in the response.</p>
          x-last-modified: 1617081816966
        '422':
          description: Account <b>NOT</b> created.  An account with that ID already exists.
          x-last-modified: 1617081968221
      operationId: create account
    x-last-modified: 1617081125216
  '/accounts/account/{id}':
    put:
      requestBody:
        description: 'The details for the account. '
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
        required: true
      tags:
        - Account
      parameters:
        - deprecated: false
          name: id
          description: Account's ID
          schema:
            type: string
          in: path
          required: true
          x-last-modified: 1617082133691
      responses:
        '204':
          description: Account successfully updated.
          x-last-modified: 1617082167170
        '404':
          description: No account matching the provided ID was found.
          x-last-modified: 1617082234845
        '409':
          description: ' <p>Account <b>NOT</b> updated.</p> <p>Modifying the account''s ID via this operation is not permitted.</p>'
          x-last-modified: 1617082266877
      operationId: update account
    delete:
      tags:
        - Account
      parameters:
        - deprecated: false
          name: id
          description: ID for the account to be deleted.
          schema:
            type: string
          in: path
          required: true
          x-last-modified: 1617082335742
      responses:
        '204':
          description: 'Account successfully deleted. '
          x-last-modified: 1617082363232
        '404':
          description: No account matching the provided ID was found.
          x-last-modified: 1617082401405
      operationId: delete acount
    x-last-modified: 1617081143511
components:
  schemas:
    Account:
      description: Details for an account.
      required:
        - id
        - ' username'
        - firstName
        - lastName
        - group
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        group:
          type: string
        uri:
          type: string
      x-last-modified: 1617081053216
  securitySchemes: {}
  headers: {}
  responses: {}
  parameters: {}
tags:
  - name: Accounts
    description: Accounts
    x-last-modified: 1617080976166
  - name: Account
    description: Account
    x-last-modified: 1617080979362
security: []
