openapi: 3.0.3
info:
  title: Sales Service API
  version: '1.0'
  description: This is a RESTful service that collects sale information received from Vend.
  x-logo:
    url: ''
  license: null
  contact: null
servers:
  - url: 'http://localhost:8081/api'
    description: ''
    variables: {}
    x-last-modified: 1616802607142
paths:
  /sales:
    post:
      tags:
        - Sales
      operationId: add sale
      summary: Add a new sale
      responses:
        '201':
          type: ''
          description: >-
            <p>Sale successfully created.</p> <p>The URI of new sale is
            available in the <code>uri</code> field of the response.  The new
            sale is returned in the response.</p>
          content:
            application/json:
              encoding: ''
              schema:
                $ref: '#/components/schemas/Sale'
          x-last-modified: 1616803117106
        '422':
          type: ''
          description: Sale <b>NOT</b> created.  A sale with that ID already exists.
          x-last-modified: 1616803179226
      requestBody:
        description: Details for the sale.
        required: true
        content:
          application/json:
            encoding: ''
            schema:
              $ref: '#/components/schemas/Sale'
    x-last-modified: 1616802816218
  '/sales/sale/{id}':
    delete:
      tags:
        - Sale
      operationId: delete
      summary: Delete sale.
      description: Delete the sale that matches the supplied ID from the sales.
      parameters:
        - name: id
          in: path
          example: ''
          required: true
          deprecated: false
          description: The ID of the sale.
          schema:
            example: ''
            type: string
            format: ''
            pattern: ''
            enum: []
          type: string
          format: ''
          pattern: ''
          enum: []
          x-last-modified: 1616804006881
    x-last-modified: 1616803401972
components:
  schemas:
    Sale:
      description: Details for a sale.
      required:
        - id
        - saleDate
      enum: []
      type: object
      properties:
        id:
          type: string
        saleDate:
          type: string
        customer:
          $ref: '#/components/schemas/Customer'
        items:
          type: array
          items:
            $ref: '#/components/schemas/SaleItem'
        totals:
          $ref: '#/components/schemas/Totals'
      example: ''
      x-last-modified: 1616619850266
    Customer:
      description: Details for a customer.
      required:
        - id
        - group
      enum: []
      type: object
      properties:
        id:
          type: String
        email:
          type: String
        group:
          type: String
      example: ''
      x-last-modified: 1616636717360
    Totals:
      required:
        - totalPrice
        - totalTax
        - totalPayment
      enum: []
      type: object
      properties:
        totalPrice:
          type: Double
        totalTax:
          type: Double
        totalPayment:
          type: Double
      example: ''
      x-last-modified: 1616636919569
    SaleItem:
      required:
        - productId
        - quantity
        - price
      enum: []
      type: object
      properties:
        productId:
          type: String
        quantity:
          type: Double
        price:
          type: Double
      example: ''
      x-last-modified: 1616637205338
    Account:
      description: Details for an account.
      required:
        - id
        - ' username'
        - firstName
        - lastName
        - group
      enum: []
      type: object
      properties:
        id:
          type: String
        email:
          type: String
        username:
          type: String
        firstName:
          type: String
        lastName:
          type: String
        group:
          type: String
      example: ''
      x-last-modified: 1616637575167
    Summary:
      required:
        - numberOfSales
        - totalPayment
        - group
      enum: []
      type: object
      properties:
        numberOfSales:
          type: Integer
        totalPayment:
          type: Double
        group:
          type: String
      example: ''
      x-last-modified: 1616638327415
  securitySchemes: {}
  responses: {}
  parameters: {}
tags:
  - name: Sale
    description: Sale
    externalDocs: {}
    x-last-modified: 1616562338993
  - name: Sales
    description: Sales
    externalDocs: {}
    x-last-modified: 1616802584737
security: []
externalDocs: null
