openapi: 3.0.3
info:
  title: Sales Service API
  version: '1.0'
  description: This is a RESTful service that collects sale information received from Vend.
  x-logo:
    url: ''
  license: null
  contact: null
servers:
  - url: 'http://localhost:8080/api'
    description: ''
    x-last-modified: 1616562420738
paths: {}
components:
  securitySchemes: {}
  schemas:
    Sale:
      example: ''
      type: object
      enum: []
      required:
        - id
        - saleDate
      properties:
        id:
          type: string
        saleDate:
          type: string
        customer:
          $ref: '#/components/schemas/Customer'
        items:
          type: array
          items:
            $ref: '#/components/schemas/SaleItem'
        totals:
          $ref: '#/components/schemas/Totals'
      description: Details for a sale.
      x-last-modified: 1616619850266
  responses: {}
  parameters: {}
tags:
  - name: Sale
    description: Sale
    externalDocs: {}
    x-last-modified: 1616562338993
security: []
externalDocs: null
